"""empty message

Revision ID: 578458551bf5
Revises: 
Create Date: 2022-06-20 15:13:14.218117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578458551bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=20), nullable=False),
    sa.Column('minerals', sa.Integer(), nullable=True),
    sa.Column('vespene', sa.Integer(), nullable=True),
    sa.Column('supply', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=300), nullable=True),
    sa.Column('unit_tier', sa.Integer(), nullable=True),
    sa.Column('unit_image', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
